//! Raw FFI bindings to whisper.cpp.
//!
//! Generated by bindgen from the vendored `whisper.h`. Nothing here is safe to
//! call without upholding whisper.cpp's own contracts -- the safe wrapper
//! lives in the engine crate; this is only the boundary.
//!
//! The important property of this crate is not its API but its *linkage*: the
//! `whisper.dll` it builds imports the same ggml that `llama-cpp-sys-2` built,
//! so both engines can be resident in one process. See PINS.md.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    /// Calling into the library at all is the point: it proves `whisper.dll`
    /// loaded, which means its ggml imports resolved against the shared ggml
    /// rather than a missing or duplicate one.
    #[test]
    fn library_loads_and_reports_its_build() {
        let info = unsafe { std::ffi::CStr::from_ptr(whisper_print_system_info()) };
        let info = info.to_string_lossy();
        assert!(!info.is_empty(), "whisper reported no system info");
    }
}
