import { useState } from "react";
import styles from "./ProjectChat.module.css";
import { Markdown } from "./Markdown";
import type { ChatDisplayMessage } from "../state/useChat";

export type ProjectChatProps = {
  project: string;
  messages: ChatDisplayMessage[];
  /** True while an answer is generating; the form disables and Stop shows. */
  streaming: boolean;
  error: string | null;
  onSend: (text: string) => void;
  onStop: () => void;
  /** Opens a cited meeting, exactly like a list row. */
  onOpenSource: (entryId: string) => void;
  /** Why chat cannot run right now (no LLM model, service down); renders as
   * a hint and disables the form. */
  disabledReason?: string;
};

/**
 * Chat with the local language model about this project's meetings.
 *
 * Answers stream in live and draw only on indexed materials (transcripts,
 * summaries, notes); each assistant turn lists the meetings it cited, and
 * clicking one opens the recording. Presentational apart from its
 * callbacks: no invoke, no listen, no fetch.
 */
export function ProjectChat({
  project,
  messages,
  streaming,
  error,
  onSend,
  onStop,
  onOpenSource,
  disabledReason,
}: ProjectChatProps) {
  const [draft, setDraft] = useState("");
  const disabled = streaming || Boolean(disabledReason);

  const submit = () => {
    const text = draft.trim();
    if (!text || disabled) return;
    setDraft("");
    onSend(text);
  };

  return (
    <section className={styles.chat} aria-label="Project chat">
      <h3 className={styles.heading}>Ask about {project}</h3>

      {messages.length === 0 ? (
        <p className={styles.empty}>
          Answers come from this project&apos;s transcripts, summaries and notes, generated by the
          local language model. Nothing leaves this machine.
        </p>
      ) : (
        <div role="log" aria-live="polite" className={styles.log}>
          {messages.map((message, index) => (
            <div
              key={index}
              className={message.role === "user" ? styles.userTurn : styles.assistantTurn}
            >
              {message.role === "user" ? (
                <p className={styles.userText}>{message.content}</p>
              ) : (
                <>
                  {message.content ? (
                    <Markdown markdown={message.content} />
                  ) : (
                    streaming &&
                    index === messages.length - 1 && (
                      <p role="status" className={styles.status}>
                        Answering…
                      </p>
                    )
                  )}
                  {message.sources && message.sources.length > 0 && (
                    <div className={styles.sources}>
                      <span className={styles.sourcesLabel}>Sources:</span>
                      {message.sources.map((source, sourceIndex) => (
                        <button
                          key={`${source.entry_id}-${sourceIndex}`}
                          type="button"
                          className={styles.sourceButton}
                          aria-label={`Open ${source.meeting_name}`}
                          onClick={() => onOpenSource(source.entry_id)}
                        >
                          [S{sourceIndex + 1}] {source.meeting_name}
                        </button>
                      ))}
                    </div>
                  )}
                </>
              )}
            </div>
          ))}
        </div>
      )}

      {error && (
        <p role="alert" className="alert">
          {error}
        </p>
      )}

      <form
        className={styles.form}
        onSubmit={(event) => {
          event.preventDefault();
          submit();
        }}
      >
        <textarea
          className={styles.input}
          aria-label="Ask about this project"
          placeholder="Когда договорились про дедлайн? Что решили по дизайну?"
          value={draft}
          disabled={Boolean(disabledReason)}
          onChange={(event) => setDraft(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter" && !event.shiftKey) {
              event.preventDefault();
              submit();
            }
          }}
        />
        <div className={styles.actions}>
          {streaming ? (
            <button type="button" className="btn btn-secondary" onClick={onStop}>
              Stop
            </button>
          ) : (
            <button type="submit" className="btn" disabled={disabled || !draft.trim()}>
              Send
            </button>
          )}
        </div>
      </form>
      {disabledReason && <p className={styles.hint}>{disabledReason}</p>}
    </section>
  );
}
