"""Allows `python -m transcription ...` to run the CLI.

The Windows installer's baked, relocatable runtime launches the service as
`<pyenv>\\python\\python.exe -m transcription serve ...` (windows-installer-build
plan, T4/T9) rather than via the `transcription-service` console-script entry
point, because console scripts generated by a package installer embed an
absolute interpreter shebang/path that breaks the moment the baked tree is
copied to its final install directory. Running the package as `-m
transcription` needs this file; `transcription/cli.py` already defines
`main()` and its own `if __name__ == "__main__"` guard for `python -m
transcription.cli` / `python cli.py`, so this module simply reuses it.
"""

from __future__ import annotations

import sys

from transcription.cli import main

if __name__ == "__main__":
    sys.exit(main())
